### ISSUE TITLE
Add check container

### ISSUE THREAD

**Issue by twiesing** [hueske-digital/restic#4]
```
  check:
    image: mazzolino/restic
    hostname: docker
    restart: unless-stopped
    environment:
      RUN_ON_STARTUP: "false"
      CHECK_CRON: "0 15 5 * * *"
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_REPOSITORY: b2:my-repo:/restic
      RESTIC_PASSWORD: supersecret
      B2_ACCOUNT_ID: xxxxxxx
      B2_ACCOUNT_KEY: yyyyyyyy
      TZ: Europe/Berlin
```
